USE [master]
GO

/****** Object:  Database [CourseManagementPortal]    Script Date: 06.02.2022 00:08:48 ******/
CREATE DATABASE [CourseManagementPortal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CourseManagementPortal', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\CourseManagementPortal.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CourseManagementPortal_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\CourseManagementPortal_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CourseManagementPortal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CourseManagementPortal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET ARITHABORT OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CourseManagementPortal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CourseManagementPortal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CourseManagementPortal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CourseManagementPortal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CourseManagementPortal] SET  MULTI_USER 
GO

ALTER DATABASE [CourseManagementPortal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CourseManagementPortal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CourseManagementPortal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CourseManagementPortal] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CourseManagementPortal] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CourseManagementPortal] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CourseManagementPortal] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CourseManagementPortal] SET  READ_WRITE 
GO

